### ISSUE TITLE
Consider promoting postgres driver to a separate folder.

### ISSUE THREAD

**Issue by bithavoc** [c4milo/migrator#1]
I think it'd be cool if we can have a directory for the postgres implementation, that way you just import the directory if you want to use postgres and other users who choose other drivers won't import the `pq` package automatically.

So If I add cassandra support, postgres will be in `https://github.com/c4milo/migrato/postgres` and cassandra in `https://github.com/c4milo/migrato/cassandra`

makes sense?

**Comment by c4milo** [comment]
that makes sense, how about using build constraints instead?

**Comment by bithavoc** [comment]
Never used build constraints before, the directory approach is very simple to understand though.

**Comment by c4milo** [comment]
I tried to use a different package. But to be honest, I think it makes more sense to use build tags for this. If you build or test your project without `-tags postgres`  or something, migrator code is going to return an explicit error given that there isn't any driver being compiled by default. I think either way serves the same purpose, being build tags the least disruptive for the project right now.

**Comment by bithavoc** [comment]
makes total sense.
