### ISSUE TITLE
consider moving migrations fixtures to test folder.

### ISSUE THREAD

**Issue by bithavoc** [c4milo/migrator#2]
at first sight the `migrations` directory looks like some required scripts for the package to work, consider moving it to a `fixtures` directory.

How about `test/fixtures` for this purpose?

**Comment by c4milo** [comment]
I would be fine with just `fixtures` as the tests are already in the root directory.

**Comment by c4milo** [comment]
Ok, I just remembered there is a reason I didn't call that folder `fixtures`. Basically, I didn't want to have to add a new parameter here: https://github.com/c4milo/migrator/blob/master/postgres.go#L99 in order for the user to specify the migrations folder she uses. Migrator requires users to use `migrations/` base path, to store their migration files (This is one of the opinionated things I refer to in the README).
